// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

RWStructuredBuffer<float3> _GrassPositionsBuffer;

Texture2D<float4> _HeightMap;
int _MeterPerPixel;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	float4 color = _HeightMap[id.xy];

	float3 pos = float3(id.x * _MeterPerPixel, id.y * _MeterPerPixel, color.r);

	_GrassPositionsBuffer[id.x + id.y * 2007] = pos;

}
